services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env.development.local
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
